import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito", // Custom CSS variable for the font
  subsets: ["latin"], // Specify the character subsets you need
  weight: ["400", "700"], // Specify the weights you need (optional)
});
export const metadata: Metadata = {
  title: "Maazady",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} font-nunito antialiased`}>
        {children}
      </body>
    </html>
  );
}
